# Generated by Django 4.1.5 on 2023-02-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='Ip del Cliente')),
                ('cedula', models.CharField(max_length=12, unique=True, verbose_name='Cedula del Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Cliente')),
                ('telefono_uno', models.CharField(max_length=12, verbose_name='Primer Telefono ')),
                ('telefonos_dos', models.CharField(blank=True, max_length=12, null=True, verbose_name='Segundo Telefono')),
                ('mensualidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mensualidad')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalacion')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('vereda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vereda')),
                ('tipo_instalacion', models.CharField(blank=True, choices=[('------', '------'), ('Fibra Optica', 'Fibra'), ('Radio Enlace', 'Radio')], max_length=20, null=True, verbose_name='Tipo de Instalacion')),
                ('status', models.CharField(blank=True, choices=[('arriba', 'Activo'), ('abajo', 'Sin servicio')], max_length=20, null=True, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMunicipio', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
            ],
            options={
                'verbose_name': 'Municpio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pueblo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Pueblo')),
            ],
            options={
                'verbose_name': 'Pueblo',
                'verbose_name_plural': 'Pueblos',
                'db_table': 'pueblo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion')),
                ('valor_pago', models.PositiveIntegerField(blank=True, null=True, verbose_name='Valor del Pago')),
                ('fecha_pago', models.DateField(null=True, verbose_name='Fecha de pago')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Valido Hasta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_Estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='cliente.estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_Municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Municipio', to='cliente.municipio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_Pueblo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pueblo', to='cliente.pueblo'),
        ),
    ]
