# Generated by Django 4.1.5 on 2023-01-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMunicipio', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
            ],
            options={
                'verbose_name': 'Municpio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('valor_pago', models.PositiveIntegerField(blank=True, null=True, verbose_name='Valor del Pago')),
                ('fecha_pago', models.DateField(null=True, verbose_name='Fecha de pago')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Valido Hasta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', to_field='cedula')),
            ],
        ),
    ]
