# Generated by Django 4.1.5 on 2023-01-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_municipio_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_Municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Municipio', to='cliente.municipio'),
        ),
    ]
