# Generated by Django 4.1.5 on 2023-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_id_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_instalacion',
            field=models.CharField(blank=True, choices=[('------', '------'), ('Fibra Optica', 'Fibra'), ('Radio Enlace', 'Radio')], max_length=20, null=True, verbose_name='Tipo de Instalacion'),
        ),
    ]
